### ISSUE TITLE
Evaluate if the dice rollers are "fair"

### ISSUE THREAD

**Issue by matanlurey** [swlegion/tts#6]
We've had multiple complaints that 1 or more of the dice rollers are providing results that are not consistent with the probability of the dice being rolled. This might be an easy fix or might require a larger investment in the dice roller (or using an "electronic" dice roller - which will be less fun).

**Comment by nashjaee** [comment]
I ran a couple simulations of the dice (just a script that spawns and rolls the dice a bunch, then outputs the data). Results are attached in the images. One of them is with bounciness=0, which is how the mod currently works. The other is changed to bounciness=1.

I had some help from Screwtape to do the actual analysis. The chi-sq test on the B=0 is in the realm of probably ok, but worthy of attention. B=1 is significantly better, as I think the extra bouncing and spinning introduces more randomness and prevents those odd situations where the dice just spin in the air parallel to the table. Not to mention it's more fun because they better reflect physical dice :)

I think it's worth considering making this the default setting on the dice. I'd also like to runner simulations with a greater number of trials.


![bounce_1](https://user-images.githubusercontent.com/8440699/66010713-f9374900-e474-11e9-90e4-19bbfce9bd90.jpg)
![bounce_0](https://user-images.githubusercontent.com/8440699/66010714-f9374900-e474-11e9-8ed1-90f7ea1c88bd.jpg)

**Comment by matanlurey** [comment]
Super cool @nashjaee thanks! I agree B=1 seems more fun.

There has been concerns that the blue dice roller is better than the red. Did you have any simulations on that?

**Comment by nashjaee** [comment]
These numbers were run using the blue roller. I can try the red one as well to compare.
